### ISSUE TITLE
Valideringsfejl  på registration side

### ISSUE THREAD

**Issue by akobberup** [sbglasius/local-dinner#1]
Når et event er oprettet og man kan teste det, får man en fejlbesked der siger at tilmeldingsfristen er overskredet selv om det ikke er tilfældet.
Man kan godt teste eventet alligevel.

![image](https://github.com/sbglasius/local-dinner/assets/5594678/78b04042-4929-475f-95b3-436f99c8998f)

**Comment by sbglasius** [comment]
Rettet og kommer med i næste version.
