### ISSUE TITLE
Tilføj autocomplete på tekstfelter i tilmelding

### ISSUE THREAD

**Issue by akobberup** [sbglasius/local-dinner#2]
Det er ikke alle felter der bliver auto udfyldt i tilmeldingen. 
Det kunne være en mulighed at ændre felternes name eller tilføje en autocomplete property:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

![image](https://github.com/sbglasius/local-dinner/assets/5594678/9295cb97-12e5-4ebf-af06-a915ad959bc5)

**Comment by sbglasius** [comment]
Fixed og bliver released om lidt
