### ISSUE TITLE
Validation fejl ved redigering af event

### ISSUE THREAD

**Issue by akobberup** [sbglasius/local-dinner#3]
Jeg prøvede at ændre "Sted" men da jeg prøvede at gemme fik jeg fejlen
"Du har ikke rettighed til at oprette eller skifte væk fra TEST." selvom det ikke var det jeg prøvede på

![image](https://github.com/sbglasius/local-dinner/assets/5594678/3eef4379-34a7-4e00-9d71-c88c02992238)

**Comment by akobberup** [comment]
Jeg kan ikke komme væk fra siden bagefter - der er ikke en "Annuller" knap.

**Comment by sbglasius** [comment]
Rettet så validering er ok, og der er nu en tilbage-knap
