### ISSUE TITLE
Der er ingen måde at åbne menuen/komme væk fra "rediger"

### ISSUE THREAD

**Issue by akobberup** [sbglasius/local-dinner#4]
Hvis man klikker på "Rediger" på hovedsiden, kommer man til en "show" url a la denne:
https://app.local-dinner.dk/dinnerEvent/show/OA8PEHfbhyhUHxWFIVjtD

Men der er ikke en måde at komme tilbage på - der er ikke en menu i toppen, og der er ikke en annuller/retur knap i bunden.

Den eneste måde er browserens tilbageknap

**Comment by sbglasius** [comment]
Er rettet til næste release
