### ISSUE TITLE
Fejl når jeg prøver at se en mail

### ISSUE THREAD

**Issue by akobberup** [sbglasius/local-dinner#5]
Jeg vil gerne ændre lidt i teksten på en email, men jeg kan ikke engang se den da der kommer en fejl:
![image](https://github.com/sbglasius/local-dinner/assets/5594678/d781839f-df95-4c55-a2ea-5f881d608416)

https://app.local-dinner.dk/communication/show/S9OEQduCCYeIsY6gvNs20

**Comment by sbglasius** [comment]
Årsag: Der er endnu oprettet fester og gæster. Nu kommer der en sigende fejlbesked i stedet for en generisk fejlside.

Klar i næste release
